# Generated by Django 6.0.5 on 2026-05-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment_post_blog_app_po_publish_df7449_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
